FROM ubuntu:16.04
MAINTAINER James Brennan <james@jamesbrennan.ca>

RUN apt-get update \
  && apt-get -y install \
    curl \
    emacs \
    git \
    jq \
    stow \
    tmux \
    wget \
    bash-completion \
  && apt-get clean

# docker client
RUN curl \
    --silent \
    --show-error \
    --create-dirs \
    --location "https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz" \
    --output "/tmp/docker.tar.gz" \
  && tar -C /usr/local/bin -xzf /tmp/docker.tar.gz --strip-components 1 \
  && rm /tmp/docker.tar.gz

# Dotfiles

RUN git clone https://github.com/Bash-it/bash-it.git ~/.bash-it \
    && git --git-dir /root/.bash-it/.git checkout 7ffb9e2

RUN git clone https://github.com/syl20bnr/spacemacs.git ~/.emacs.d \
    && git --git-dir /root/.emacs.d/.git checkout c2774bc

RUN git clone https://github.com/jpb/dotfiles.git /root/.dotfiles \
    && git --git-dir /root/.dotfiles/.git checkout 9e5b490 

RUN rm ~/.bashrc  \
   && cd /root/.dotfiles \
   && stow emacs \
           git \
           tmux \
           bash

RUN emacs -nw -batch -u root -q -kill && \
    sed -i "s/dotspacemacs-install-packages 'all/dotspacemacs-install-packages 'used-but-keep-unused/g" \
      ${HOME}/.spacemacs && \
    emacs -nw -batch -u root -q -kill

COPY bin /root/bin

ENV TERM screen-256color
ENV LANG en_US.UTF-8
ENV PATH /root/bin:$PATH
ENV SHELL /bin/bash
ENV EMACS_SERVER_FILE /tmp/emacs-docker/server.sock
ENV ALTERNATE_EDITOR emacs
ENV EDITOR emacsclient

ENTRYPOINT ["tmux"]
CMD ["new", "-s", "dev"]