FROM ubuntu:16.04
MAINTAINER James Brennan <james@jamesbrennan.ca>

RUN apt-get update \
  && apt-get -y install \
    bash-completion \
    curl \
    dnsutils \
    emacs \
    git \
    jq \
    libffi-dev \
    make \
    mysql-client \
    man \
    netcat \
    python \
    python-openssl \
    python-pip \
    silversearcher-ag \
    stow \
    tmux \
    wget \
  && apt-get clean

RUN git clone --depth 1 https://github.com/sstephenson/bats.git /tmp/bats \
  && /tmp/bats/install.sh /usr/local \
  && rm -rf /tmp/bats

RUN LC_ALL=C pip install --upgrade pip
RUN LC_ALL=C pip install ansible boto boto3 yamllint jedi

# Docker Client

RUN curl \
    --silent \
    --show-error \
    --create-dirs \
    --location "https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz" \
    --output "/tmp/docker.tar.gz" \
  && tar -C /usr/local/bin -xzf /tmp/docker.tar.gz --strip-components 1 \
  && rm /tmp/docker.tar.gz

# Docker Compose

RUN curl -L "https://github.com/docker/compose/releases/download/1.10.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
  && chmod +x /usr/local/bin/docker-compose

# kubectl

RUN curl -L "curl -O https://storage.googleapis.com/kubernetes-release/release/v1.5.4/bin/linux/amd64/kubectl" -i /usr/local/bin/kubectl \
  && chmod +x /usr/local/bin/kubectl

# Dotfiles

RUN git clone https://github.com/Bash-it/bash-it.git ~/.bash-it \
    && git --git-dir /root/.bash-it/.git checkout 7ffb9e2

RUN git clone https://github.com/syl20bnr/spacemacs.git ~/.emacs.d \
    && git --git-dir /root/.emacs.d/.git checkout c2774bc

RUN git clone https://github.com/jpb/dotfiles.git /root/.dotfiles \
    && git --git-dir /root/.dotfiles/.git checkout 58ed699 \
    && git --git-dir /root/.dotfiles/.git checkout master

RUN rm ~/.bashrc  \
   && cd /root/.dotfiles \
   && stow emacs \
           git \
           tmux \
           bash

RUN emacs -nw -batch -u root -q -kill # && \
    # sed -i "s/dotspacemacs-install-packages 'all/dotspacemacs-install-packages 'used-but-keep-unused/g" \
    #   ${HOME}/.spacemacs && \
    # emacs -nw -batch -u root -q -kill

COPY bin /root/bin

ENV TERM screen-256color
ENV LANG en_US.UTF-8
ENV PATH /root/bin:$PATH
ENV SHELL /bin/bash
ENV EMACS_SERVER_FILE /tmp/emacs-docker/server.sock
ENV ALTERNATE_EDITOR emacs
ENV EDITOR emacsclient

ENTRYPOINT ["tmux"]
CMD ["new", "-s", "dev"]
