FROM alpine:3.4
MAINTAINER James Brennan <james@jamesbrennan.ca>

RUN apk add --no-cache \
    build-base \
    coreutils \
    curl \
    findutils \
    git \
    grep \
    jq \
    less \
    make \
    openssh-client \
    rsync \
    tar \
    tmux \
    unzip \
    util-linux \
    wget \
    bash

ENTRYPOINT ["bash"]
