FROM alpine:3.5
MAINTAINER James Brennan <james@jamesbrennan.ca>

RUN apk add --no-cache \
    bash \
    build-base \
    coreutils \
    curl \
    findutils \
    git \
    grep \
    jq \
    less \
    make \
    man \
    openssh-client \
    rsync \
    tar \
    tmux \
    unzip \
    util-linux \
    wget

ENTRYPOINT ["bash"]
